name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: HadenSmith/doxygen-github-pages-action@v2.0.0
        with:
          branch: gh-pages
          folder: docs/Doxygen/html
          config_file: Doxyfile
